### ISSUE TITLE
Cannot access .json paths

### ISSUE THREAD

**Issue by pusewicz** [balvig/spyke#10]
Cannot access paths generated like this:

``` ruby
class Profile < Spyke::Base
  uri '/1/profiles(/:id).json'
end
```

**Comment by balvig** [comment]
@pusewicz thanks for reporting this! 

Spyke uses the colon based syntax of [uri_template](https://github.com/hannesg/uri_template) which unfortunately currently only has limited support for optional fragments, and including slashes in the fragment is not possible at the moment... :cry: 

A couple of suggestions on how you can solve your problem (in order of most to least desirable :grin: ):

1. Submit a PR to uri_template adding support for optional fragments when using the colon syntax. The repo has [an issue related to this ](https://github.com/hannesg/uri_template/issues/9) that sadly seems to have gone stale...
2. Somehow add the functionality directly to Spyke. [path.rb](https://github.com/balvig/spyke/blob/master/lib/spyke/path.rb) would be a good place to start and I've [added a failing spec](https://github.com/balvig/spyke/commit/4a929d34ccae6f493181ab6088ff788f0309ae7b) covering the scenario to work from.
3. If the API you're connecting with is a Rails app, try setting the accept header to `application/json` and dropping the `.json` extension from the url. In theory Rails should be able to understand this and return the correct format.
4. Try using `/1/profiles/(:id).json` instead, it won't give you the url you want for collections (will result in `/1/profiles/.json`) but at least it will work for profiles that have an ID.

**Comment by gottfrois** [comment]
From an external point of view, I would say setting `application/json` is the way to go to solve the issue.

**Comment by pusewicz** [comment]
@gottfrois Unless you are not in the control, and you can't!

**Comment by gottfrois** [comment]
right :)

**Comment by chriso0710** [comment]
Maybe there is another good and reasonable option: 

Exchange ```uri_template``` for https://github.com/sporkmonger/addressable.
Addressables URI templates seem to handle this case well:

```ruby
template = Addressable::Template.new("/1/profiles{/id}.xml")
 => #<Addressable::Template:0x3fe4550c0c14 PATTERN:/1/profiles{/id}.xml> 
template.expand({})
 => #<Addressable::URI:0x3fe4558b0208 URI:/1/profiles.xml> 
template.expand({ :id => "2"})
 => #<Addressable::URI:0x3fe455543110 URI:/1/profiles/2.xml> 
```

What do you think? Did I miss something here?
As I need this for my current project I would be trying to change ```Path``` and provide a PR.

**Comment by balvig** [comment]
Thanks for looking into this @chriso0710! 
Looks like that might do the job 😄 
 If we can preserve the `/recipes/(:id)` syntax I would be extra happy 🎉

**Comment by balvig** [comment]
Closed in https://github.com/balvig/spyke/pull/88
