### ISSUE TITLE
More flexible parsing of responses per-model

### ISSUE THREAD

**Issue by julioolvr** [balvig/spyke#102]
The case I'm trying to work around is when the API response keys depend on the specific resource, e.g.:

```
GET /users
{ "users": [...], "total": 20 }

GET /posts
{ "posts": [...], "total": 200 }
```

So, the data for each response is under a key that depends on the specific model being queried. I don't think that's possible given that the key has to be known at the Faraday middleware level. The way I'm working around this is by returning the whole response as `data` (which I'm not too fond of, since it might cause issues when Spyke sees that `data` is a hash and not an array), and then on each class override `new_collection_from_result` to do something like `result.body[:data] = result.data['users']` before calling `super`.

So I guess my first question is whether there's already a better way and if there isn't, if it sound like something that could be useful. My first thought would be to be able to define a lambda on each model to extract the data field from the response, but I'm not sure how that would impact performance.

**Comment by balvig** [comment]
Aha, interesting! 

A couple of potential solutions off the top of my head (not sure if they’re any good though 😅):

## Use different middleware for each resource

You can use a different Faraday middleware for each resource, as [described here](
https://github.com/balvig/spyke#using-multiple-api). Each of them can parse the result in different ways.

## Make your own custom Faraday instance

You could inherit from `Faraday` and create your own instance. I’m not in front of a terminal so it’s a bit hypothetical, but perhaps you could pass in the class and do something with it when parsing the result. Ie:


```ruby
class MyCustomFaraday > Faraday
  def initialize(resource:, url:)
     @resource = resource
     super(url: url)
  end
end
```

## Try out all keys in the middleware

Not great, but kinda what you’re already doing, except without having to override anything.

Following [the docs](https://github.com/balvig/spyke#configuration), you could do something like:

```ruby
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    {
      data: json[:users] || json[:posts] # || ...
    }
  end
end
```

Let me know if this gives you any ideas, probably thinking about it some more could lead to some better options! 🙇

**Comment by julioolvr** [comment]
Interesting! I can see the first approach being pretty useful if extracted to a concern or similar, I'll be looking into it 👌

**Comment by balvig** [comment]
Hope that worked out for you! Closing the issue for now 🙏
