### ISSUE TITLE
uninitialized constant JSONParser::MultiJson

### ISSUE THREAD

**Issue by dayvough** [balvig/spyke#108]
Running ruby 2.6.3 and rails 6rc1, without installing the `multi_json` gem, I run into this error

```
uninitialized constant JSONParser::MultiJson
```

**Comment by balvig** [comment]
Thanks @dayvough! Should be addressed in https://github.com/balvig/spyke/commit/bbc7810c44bdf5bf77b3eec79fbf6389f4eca519
