### ISSUE TITLE
Building has_many association on model from nested attributes does not work with Strong Params

### ISSUE THREAD

**Issue by zeiv** [balvig/spyke#111]
I have a model which `has_many: :program_location_rooms` and `accepts_nested_attributes_for :program_location_rooms`.
Given the following form:

```rb
<%= simple_form_for @program_location, url: em_program_locations_path, html: {id: "form_for_mappable_1"} do |f| %>
  <%= f.simple_fields_for :program_location_rooms do |ff| %>
    <%= ff.input :room, wrapper_html: {class: "col"} %>
    <%= ff.input :capacity, wrapper_html: {class: "col"} %>
  <% end %>
<% end %>
```

The model will have the `program_location_rooms` attribute defined like this:

`program_location_rooms: [#<EM::ProgramLocationRoom() id: nil program_location_id: nil 0: nil {"room"=>"101", "capacity"=>"32"}: nil>]`

![image](https://user-images.githubusercontent.com/1824972/70346446-f6b1f080-1823-11ea-877d-b4942e82d20c.png)

The expected result is this:

`program_location_rooms: [#<EM::ProgramLocationRoom() id: nil program_location_id: nil room: "101" capacity: "32">]`

![image](https://user-images.githubusercontent.com/1824972/70346569-3aa4f580-1824-11ea-9697-8e21786b2e88.png)

I think I've figured out the solution, will submit a PR shortly

**Comment by mattboldt** [comment]
This should probably be closed if this PR is fixed https://github.com/balvig/spyke/pull/115
