### ISSUE TITLE
Cannot use `find` with required parameters

### ISSUE THREAD

**Issue by davefp** [balvig/spyke#113]
I have a resource that is always nested under a parent, whose path looks like this: `parent/:parent_id/child(/:id)`

I cannot use `find` to fetch individual instances of the child resource since `find` can only take a single param, the primary key.

I can work around it by calling `where(parent_id: parent_id, primary_key: child_id).find_one`, but it would be convenient to be able to do `find(child_id, parent_id: parent_id)` instead.

**Comment by balvig** [comment]
@davefp ah, the convention here is to emulate Rails by doing:

```rb
where(parent_id: 1).find(2)
```

which should then resolve to `GET /parent/1/child/2`.

Hope that helps!

**Comment by davefp** [comment]
That makes a lot of sense, thanks for the help!
