### ISSUE TITLE
How to handle errors in a spyke relation

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#14]
I dont know for sure, but It seems spyke does not delegate the method errors in relation.rb. I think that is the reason I am unable to access Spyke::Relation.errors in my environment. This is happening, because I have a authorization policy where I need to pass some token to my api, and when I dont, it retuns a error in my index action, but Spyke is not getting this in errors method, actually, below follows its messages. BTW, I need to know if it is possible to use some default middleware to handle with authentication, something like what it is describe in HER readme? is it the same?

```ruby
NoMethodError: undefined method `errors' for #<Spyke::Relation:0x000000024dc860>
from /home/thiagocifani/.rvm/gems/ruby-2.1.2@sigvia/gems/spyke-1.8.3/lib/spyke/relation.rb:48:in `method_missing'
```

**Comment by thiagocifani** [comment]
Answering my on question about authentication, It is the same as in HER. The error still persist, any help will be appreciate, but it seems I will need to delegate itself in relation, but I would like if you give me any tip.

**Comment by balvig** [comment]
Could you show what the code that causes the error looks like, and what the errors returned looks like?
Re authorization, like Her, Spyke uses Faraday so yes you can do all the same things :smile:

**Comment by thiagocifani** [comment]
Hey @balvig , my current problem is something like this: 

https://gist.github.com/thiagocifani/7a3573261fa559d35f54

**Comment by thiagocifani** [comment]
It was a error of mine. forget it. Thanks again
