### ISSUE TITLE
bin/console name conflicts with every other gem's console 

### ISSUE THREAD

**Issue by MadBomber** [balvig/spyke#142]
Its nice to have a console .... but do they all have to be named "console?"

Do you mind changing the name to spyke_console to avoid the conflicts with other gem's console?

**Comment by balvig** [comment]
@MadBomber sorry, I think I'm missing something, but I'm not sure I fully follow how this conflict occurs? 
`bin/console` is what is generated for any gem when using `bundle gem <GEM NAME>`.
https://github.com/rubygems/bundler/blob/35be6d9a603084f719fec4f4028c18860def07f6/UPGRADING.md?plain=1#L77-L83

**Comment by MadBomber** [comment]
the gem spec needs to be updated so that the local bin directories is not put on the system path. Or the names of the executable’s need to be name spaced for the gym otherwise, since so many other jams, also have a consul or set up in their been directly, and the same problem in their gym spec play all conflict with each other     please pardon the poor speech to text rendition. Dewayne   o-*On Jun 11, 2023, at 7:56 PM, Jens Balvig ***@***.***> wrote:﻿
@MadBomber sorry, I think I'm missing something, but I'm not sure I fully follow how this conflict occurs?
bin/console is what is generated for any gem when using bundle gem <GEM NAME>.
https://github.com/rubygems/bundler/blob/35be6d9a603084f719fec4f4028c18860def07f6/UPGRADING.md?plain=1#L77-L83

**Comment by balvig** [comment]
Thank you @MadBomber, got it! #143
