### ISSUE TITLE
Query params for DELETE action

### ISSUE THREAD

**Issue by amalagaura** [balvig/spyke#147]
I am accessing a REST API which takes query parameters on the DELETE action: 

https://docs.camunda.org/manual/7.5/reference/rest/deployment/delete-deployment/

It is supported in [HER](https://github.com/remi/her/blob/b59a05aa12ac9da44d4d51dcfbbfb7c67a4a156a/lib/her/model/orm.rb#L4)

I created this Pull Request #145

**Comment by balvig** [comment]
Closed in https://github.com/balvig/spyke/pull/145
