### ISSUE TITLE
Dynamic Multi-API Support

### ISSUE THREAD

**Issue by pboling** [balvig/spyke#154]
We have complex cloud infrastructure.  Currently we use Her, but highly customized.

Our API endpoints can change on every request (for failover, or distribution, or isolation, or specific multi-tenancy-related URL parts, etc) and we actually have a secondary endpoint that determines what endpoint should be used for the Her/Spyke request.

All that complexity is required because we push so much data around at massive volumes.

So for us `connection` needs to be a lambda that is called every time it is used, and the API will be changing every request, for every model.

I'm going to work on a PR, but wanted to get your thoughts @balvig.  Thanks for keeping this going for so many years!

**Comment by pboling** [comment]
This library is wonderfully easy to extend.  Cheers!  It is done!

https://github.com/pboling/spyke-connection_lambda

**Comment by balvig** [comment]
That's awesome @pboling! 👏 

I also have a feeling that you _might_ be able to achieve this with Faraday middleware, modifying the URL on the fly.
This is pseudocode, but I think something like this could work:

```rb
class DynamicURLMiddleware < Faraday::Middleware
  def call(env)
    env[:url].path = "/new/path"
    @app.call(env)
  end
end
```

**Comment by pboling** [comment]
I expect that would work in certain use cases, but we also need it per model, so it is easier to localize the lambda in each model.
