### ISSUE TITLE
Minimum Ruby Version

### ISSUE THREAD

**Issue by pboling** [balvig/spyke#155]
Find out what it is and set it in the gemspec!

Due to the addressable [version constraint](https://rubygems.org/gems/addressable/versions/2.5.2) it is at least Ruby >= 2.

The oldest least hassle version of Ruby to test with on GitHub Actions (in my experience) is Ruby 2.3.

**Comment by balvig** [comment]
Cheers @pboling!
Maybe take a look at https://github.com/balvig/spyke/pull/156
As mentioned, Spyke is tested in CI on `2.6.9` as the oldest version.
It's possible that it might work on older versions, but haven't had the opportunity to try!
