### ISSUE TITLE
Yanked version 7.2.0 & 7.2.1 on RubyGems

### ISSUE THREAD

**Issue by julienfromentc** [balvig/spyke#159]
Hello,

I have noticed that version 7.2.0 and 7.2.1 were yanked from RubyGems, which broke our CI/CD pipelines for our application.

![image](https://github.com/balvig/spyke/assets/514808/6346498a-3ceb-4116-a1ea-d0ad18f77a47)

Is there any reason why those 2 versions were yanked?

**Comment by balvig** [comment]
Hey @julienfromentc!
I am sorry to hear this broke your builds! 🙇  
Thanks for getting in touch.

Those two versions inadvertently included a breaking change: https://github.com/balvig/spyke/pull/145#issuecomment-2046181770.

Sorry for the hassle, but you can most likely safely upgrade to `7.2.3`, as it merely reverts that breaking change.
Changelog here: https://github.com/balvig/spyke/releases

**Comment by julienfromentc** [comment]
Thanks you for the information, i'll be closing the issue.

Personally, yanking the old version caused us more issue than keeping it, because we were not using the feature that was reverted. We actually started using the gem with version 7.2+, so technically "upgrading" to 7.2.2 could have introduced a regression it our application.

**Comment by balvig** [comment]
@julienfromentc yeh, that makes sense. Was a tricky call!
Hope you're all set now 🙏
