### ISSUE TITLE
Strip id slug should be optional

### ISSUE THREAD

**Issue by gottfrois** [balvig/spyke#16]
Hey guys,

I have a scenario where my resource ids are strings with dashes. Unfortunately the gem will only take the first part of my id because of this code: https://github.com/balvig/spyke/blob/master/lib/spyke/orm.rb#L47

Here is an example:

```ruby
> Content.find('foo-bar')
Spyke::ResourceNotFound: Spyke::ResourceNotFound
```

Would it be possible to have this as a configuration?

**Comment by balvig** [comment]
Hmmm, that's interesting, I haven't actually come across an API that requires strings before! :smile: 

When you get back the resource, is the ID of that resource also returned as a string? (otherwise I imagine problems might occur if you try to update it etc, as Spyke will use `content.id` to generate the URL for updates)

**Comment by gottfrois** [comment]
It's actually how the API is built.

The show endpoint takes an id which in my case is the name of the resource as a string (ex: `foo`). The resource also has a real id (mongodb id in my case). But my business use case is easier to solve if using the resource name as the id.

I tried to achieve the same behavior with the index endpoint, applying a filter (`/contents?name=foo`) but this means I would need to include all the details the show endpoint return in the index endpoint...

**Comment by balvig** [comment]
Aha, I see. How about if you add a custom `find_by` method to your `Content` class and use it along with a custom URI to solve the problem? Ie something like:

```ruby
class Content < Spyke::Base
  uri '/contents/:slug'

  def self.find_by(slug:)
    where(slug: slug).find_one
  end
end
```

This should allow you to do:

```ruby
Content.find_by(slug: 'foo-bar') # => GET /contents/foo-bar
```

**Comment by gottfrois** [comment]
works great, thanks !
