### ISSUE TITLE
infer class name association

### ISSUE THREAD

**Issue by gottfrois** [balvig/spyke#17]
Hi,

I have two models deeply nested into modules, unfortunatelly I need to explicitely pass the class name when defining associations. It would be great if the class name of the association was infer from the parent modules:

```ruby
module A
  module B
    class Page < Spyke::Base
      has_many :contents, class_name: 'A::B::Content'
    end
  end
end
```

```ruby
module A
  module B
    class Content < Spyke::Base
    end
  end
end
```

Would be great to be able to do `has_many :contents` and let the gem infer the class name based on the parent nested modules.

The code responsible for this seems to be here https://github.com/gottfrois/spyke/blob/098426992102c38e3068be6cb75d9636846c1b9f/lib/spyke/associations/association.rb#L10

**Comment by balvig** [comment]
Good point, certainly seems like that should "just work" :)

Was trying to find out how it works in ActiveRecord, but (provided I'm looking at the right location) looks [rather complicated](https://github.com/rails/rails/blob/70ac072976c8cc6f013f0df3777e54ccae3f4f8c/activerecord/lib/active_record/inheritance.rb#L130-L150)...

If you're up for having a go at a pull request, would be welcome! :smile:

**Comment by gottfrois** [comment]
yep looks like it :)

**Comment by balvig** [comment]
@gottfrois this is now supported in [1.8.6](https://github.com/balvig/spyke/compare/v1.8.5...v1.8.6), thanks for reporting! :smiley:

**Comment by gottfrois** [comment]
Oh man super nice, well done :)
