### ISSUE TITLE
Define uri in base class and extend it from sub-classes

### ISSUE THREAD

**Issue by gottfrois** [balvig/spyke#18]
Hi,

I defined a base class to handle my models like so:

```ruby
module Models
  class Base < Spyke::Base
  end
end
```

and then inherits from it in my models:

```ruby
module Models
  class Content < ::Models::Base
  end
end
```

All my models will follow the same `uri` schema (ex: `uri "/api/v1/constants/(:name)"`). Is it possible to define the base uri schema in the parent class?

```ruby
module Models
  class Base < Spyke::Base
    uri '/api/v1/'
  end
end
```

and then extend it in each sub-classes.

**Comment by balvig** [comment]
Fixed in #19 / Gem v. 1.8.4.

Thanks for reporting! :wink:
