### ISSUE TITLE
Change API uri subdomain on the fly

### ISSUE THREAD

**Issue by thibaudgg** [balvig/spyke#20]
Hey,

Our API backend uses subdomain for separating customer, so I would need to switch subdomain on the fly. Something like `Model.with_subdomain('foo').all` would be great.

With `her` I was able to change `her_api.connection.url_prefix` on the fly, but with Spyke changing `connection.url_prefix` don't work.

What do you thing about adding a method to set the url per request?

Thanks!

**Comment by balvig** [comment]
Oh, that's interesting, in theory it should be the same as it seems `url_prefix` is a method of Faraday and both Spyke and Her uses Faraday. How is it failing you? :)

**Comment by thibaudgg** [comment]
If I try to re-set `Spike::Config.connection.url_prefix` with another subdomain the logger is still printing request to the previous sudomain (same on my API server), so it seems to be cached/memoized somewhere in Spyke.

**Comment by balvig** [comment]
@thibaudgg I hope #29 fixed this for you!

**Comment by thibaudgg** [comment]
:+1: thanks!
