### ISSUE TITLE
JSON API format support.

### ISSUE THREAD

**Issue by thibaudgg** [balvig/spyke#21]
I would just be curious to know your opinion about http://jsonapi.org and if you think supporting that with Spyke.

**Comment by balvig** [comment]
I'm unfortunately not familiar with jsonapi or currently interacting with any API using that format. What would be missing from Spyke in order to support it?

**Comment by thibaudgg** [comment]
The support for associations ([Compound Documents](http://jsonapi.org/format/#document-structure-compound-documents)) would be great. There's already a gem supporting it (https://github.com/jsmestad/jsonapi-consumer), but support from Spyke could be nice.

Anyway, I recommend you to read the [format page](http://jsonapi.org/format) as it will be soon reach 1.0.0 (RC2 now) and will be supported out-of the box by `ember-data`. Thanks for your time!

**Comment by balvig** [comment]
Thanks for telling me about it! Will take a look :smile: 
Currently I'm not personally interacting with an API that follows that format but who knows, maybe sometime in the near future :+1:

**Comment by thibaudgg** [comment]
@balvig you're welcome. Thanks for your time!

**Comment by freiden** [comment]
@balvig Did you move further on a way to make spyke able to interact with JsonAPI?

**Comment by balvig** [comment]
@freiden unfortunately not! I still haven't had the need to work with a JsonAPI, so for me at least currently Spyke serves its purpose 😅
