### ISSUE TITLE
Calling association on new object gives Spyke::InvalidPathError

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#26]
I have a suggestion. There might be reasons for the current behaviour that I'm not aware of, but given the following:

````
module Wrapper
   class Book < Spyke::Base
      belongs_to :author
   end

   class Author < Spyke::Base
   end
end
```

I would expect the following behaviour:
````
b = Wrapper::Book.new
b.author # => #<#<Class:#<Wrapper::Author:0x00000101300348>>:0x809801a4>
````
That would seem to match how ActiveRecord behaves. Instead I get:
````
b = Wrapper::Book.new
b.author # => Spyke::InvalidPathError: Missing required params: id in /authors/:id. Mark optional params with parens eg: (:param)
```

So, in other words, my suggestion is that if an association is requested without a foreign_key set on the parent, Spyke builds the associated object so that it can be used to set attributes on.

I've been trying to track down where this could be done in Spyke, and it seems to me that fetch_embedded would be the right place, and that it would actually already do what I expect if ```!uri```returned true, but I can't figure out when it would to that. When would an association not have a uri set?
````
   def fetch_embedded
      if embedded
         Result.new(data: embedded)
      elsif !uri
         Result.new(data: nil)
      end
   end
```

**Comment by balvig** [comment]
I think maybe my expectation is _slightly_ different :sweat_smile:  
For the belongs_to example, in AR I would expect:

```ruby
b = Wrapper::Book.new
b.author # => nil
```

...since no author exists yet.

What Spyke _does_ support, which is what it sounds like you want to do, is `build_foo`, so you could do

```ruby
book.build_author
book.author.name = 'Luke Rhinehart"
```

Regarding associations and having uris set, the way Spyke works (which is perhaps badly documented in the [readme](https://github.com/balvig/spyke/blob/31878e5a946c3fd65471551d4abf8a066bca4fe3/README.md#custom-uris)), is if the uri is set, it will look first for data embedded in the parent JSON, and then call out to an endpoint if it doesn't find it. If not, it will _only_ use embedded JSON and never call out to the API.

In a current project we have an API that _only embeds_ data for certain associations in the returned JSON, and so although we map them to objects using Spyke, we never want to try to call out to any endpoints for these, since they simply don't exist! Therefore we set the uri to `nil`.

Hope this answers your question...? :sweat_smile:

**Comment by jontebol** [comment]
You're absolutely right about how AR behaves of course. Nil would be just fine. :) The problem with the current behaviour is that it's not possible to check if the author exists without having to rescue Spyke::InvalidPathError, which is exactly the use-case I had. So if you get Book params from the user and need to check if you should build an author or not it gets cumbersome.

**Comment by jontebol** [comment]
I'm not sure I follow exactly what you're saying about the uri being nil. Do you mean that if I never intend to fetch Dogs from the API THROUGH the owner (as in owner.dogs => api-call), but only get them embedded when fetching an owner, I should:

````
class Owner < Spyke::Base
   has_many :dogs, uri: nil
end

class Dog < Spyke::Base
   belongs_to :owner
   # how about here? uri: nil as well? I guess it depends?
end
```

If so, it seems logical, and it's definitely a common use case (I'm going to need it soon) and it should probably be in the readme, yes. :)

**Comment by balvig** [comment]
>  Do you mean that if I never intend to fetch Dogs from the API THROUGH the owner

Yep, exactly! :smile: It is indeed [mentioned in the readme](https://github.com/balvig/spyke#custom-uris) but perhaps not clearly enough :sweat_smile:

Does this clear things up...?

**Comment by jontebol** [comment]
It does indeed. When using uri: nil on associations they behave like I would expect. :) It's such an important feature that I would recommend making it super clear in the readme. :) I changed the title of this issue to something googleable for other's who might make the same mistake.

**Comment by balvig** [comment]
Thanks! And glad things worked out :+1:

**Comment by jontebol** [comment]
Hi again! It would be really nice if associations without required params also returned nil, like you said:
```ruby
b = Wrapper::Book.new
b.author # => nil
```
'Cause it would allow for code like this:
```ruby
b.build_author unless b.author
b.author.name = "Stephen King"
```

What do you think?

**Comment by balvig** [comment]
Hey! :)

It works for an association that isn't set up to call out to an api (ie `belongs_to :author, uri: nil`) but for an association that is associated with an api endpoint I'm not sure I see how it can determine if the author is there or not without trying to talk to the API?

**Comment by jontebol** [comment]
Well basically, I'm thinking if there is no foreign key, or in other words, any time a Spyke::InvalidPathError would be raised, it would just return nil instead. If you don't have the key/id, you can't ask the api for it anyway, so there is no way to determine if it is there or not, right? I mean, in this case, the API takes the role of the db in active-record, right? So if AR can return nil on an association if there is no foreign key, shouldn't Spyke be able to as well?

**Comment by jontebol** [comment]
It's no biggy of course, but currently, I have to use code like this:

```ruby
   invoice = Invoice.new(invoice_params)
      unless invoice_params[:client]
        invoice.client = {}
        invoice.client.address = {}
      else
        invoice.client.address = {} unless invoice_params[:client][:address]
      end
```

It would be a lot nicer to be able to do:

```ruby
   invoice = Invoice.new(invoice_params)
   invoice.build_client unless invoice.client
   invoice.client.build_address unless invoice.client.address
```

**Comment by balvig** [comment]
>  if AR can return nil on an association if there is no foreign key, shouldn't Spyke be able to as well

Yeh, you're right and I see what you mean! 

I have been in situations though where I've for example been trying to create an association and not realize I didn't have a foreign key, in which case the exception is useful for debugging, so would have to find a way to make that work at the same time I guess. Conversely I haven't had a need for your example which is probably why I've been ignoring it!! :smile: 

You're welcome to have a crack at it of course ;)

Meanwhile, for your example, maybe you could just do:

```ruby
class Invoice < Spyke::Base
  belongs_to :client

  def client
    super if client_id?
  end
end
```

or something like that?

**Comment by jontebol** [comment]
That's a good suggestion, I think I will do something like that for now. :) I get what you mean with the debugging-help the error provides. If I am sufficiently annoyed at some future date I might try to do something about it, but for now I'm more than happy with your suggested workaround. ;)

**Comment by balvig** [comment]
> If I am sufficiently annoyed at some future date I might try to do something about it

:+1: That's usually my modus operandi as well :wink:
