### ISSUE TITLE
Attributes on has_many objects don't "stick" unless created with build

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#28]
Me again... ;)

Given:
```Ruby
class Owner < Spyke::Base; has_many :dogs; end; class Dog < Spyke::Base; belongs_to :owner; end
````
and
```Ruby
o = Owner.new; o.dogs.build(name: "Fred")
o.dogs.first.name = "Teddy"
o.dogs.first.name # => "Teddy"
`````
I would expect the same from this code:
```Ruby
o = Owner.new(dogs: [{name: "Fred"}])
o.dogs.first.name = "Teddy"
o.dogs.first.name # => "Fred" - not what I'd expect...
`````

**Comment by balvig** [comment]
For this, like ActiveRecord, you would need to use `accepts_nested_attributes_for`, and this should hopefully give you the expected result:

```ruby
class Owner < Spyke::Base 
  has_many :dogs
  accepts_nested_attributes_for :dogs
end

o = Owner.new(dogs_attributes: [{name: "Fred"}])
o.dogs.first.name = "Teddy"
o.dogs.first.name # => "Teddy"
```

Not documented anywhere except [the tests](https://github.com/balvig/spyke/blob/2250cf4176cead26c636d1e3a9030591b15d4c84/test/associations_test.rb#L284-L353) I guess :sweaty_smile:, but more or less works like a less feature-rich version of the ActiveRecord one.

Who names their dog "Fred" anyway? :dog: :stuck_out_tongue_winking_eye:

**Comment by jontebol** [comment]
Are you bullying my dog?! :P

Indeed, this is exactly what I wanted. I did see it in the tests, and I think I even tried it... but I think I forgot to add the "_attributes" suffix. I still don't quite see why it wouldn't work in the other case though, without ```accepts_nested_attributes_for```. It's like, if there's a setter method there, and it doesn't complain when you use it, you'd expect it to set the value.

This is also something that would be nice to have in the readme yes... ;)

In case someone (like me) would like to not have to use the '_attributes' suffix, you can just do this in your model:
```Ruby
def dogs=(attrs)
   send(:dogs_attributes=, attrs)
end
```

**Comment by balvig** [comment]
In ActiveRecord you would get a `ActiveRecord::AssociationTypeMismatch: Dog(#70360803527000) expected, got Hash(#70360724851840)` exception. I guess it would be nice to have that level of feedback in Spyke too, going to have to say "PRs welcome" on that one for now :sweat_smile: 

Not sure I recommend overriding the setter, as I'm not sure what side effects that might have! I would personally stick to using the ActiveRecord-ish "accepts_nested_attributes", but of course it's up to you ;)

Cheers to Fred! :dog:

**Comment by jontebol** [comment]
I know, it might be a bit risky, but it seems to work just fine so far. I'll let you know if I run into troubles.

I was only pulling your leg. Don't have a dog a t m, but if I ever do I might just name him Fred after this... ;)
