### ISSUE TITLE
Restricting the http methods exposed

### ISSUE THREAD

**Issue by pedelman** [balvig/spyke#30]
I am working with a restful api and some of the resources don't have certain actions available to them, i.ie create, destroy, update...

Is there a configuration to restrict some of these actions from getting called on a class which inherits from Spyke::Base? My server will respond with an error, but I would rather prevent this action to save a network call.

**Comment by pedelman** [comment]
Also is there a way to format the put/post to prevent the object from being scoped to the resources?

eg.

```
User.create(name: 'Bob')
# => POST http://api.com/users - { user: { name: 'Bob' } }
```

becomes:

```
User.create(name: 'Bob')
# => POST http://api.com/users - { name: 'Bob' }
```

**Comment by balvig** [comment]
I'm not sure what the use case is, but I suppose you could override these methods in a base class and inherit from that or create a module that you include containing something like:

```ruby
def self.create
  raise 'Create not supported'
end
```

**Comment by pedelman** [comment]
What are your thoughts on a DSL to specify which actions a resource responds to. I.e. an API which only supports read actions, one with full crud abilities, etc.

**Comment by balvig** [comment]
No thoughts really! :smile: Not sure why you need to restrict it really, you couldn't just _not_ use these? :sweat_smile:

**Comment by balvig** [comment]
In any case this feels like something that doesn't need to be the responsibility of Spyke, hope you don't mind if I close this issue for now! :palm_tree:
