### ISSUE TITLE
More examples/references in the readme

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#32]
Some suggestions for the Readme:

- [x] Mention ```include_root_in_json``` somewhere.
- [x] Mention how Spyke::Base has a connection method (which delegates to Spyke::Config.connection) that can be overriden for multi-API support.
- [x] Include a link to https://github.com/balvig/spyke/blob/master/test/support/fixtures.rb because that is a great example of usage.

There's a whole backstory for this issue, which I will add as a comment. :)

**Comment by jontebol** [comment]
When I first started my client lib project (which will be released as it's own gem) I evaluated both Her and Spyke. I even went so far as to write a little benchmark to check parsing performance, in which Spyke won easily over Her. But Her was easy to set up and get to do what I wanted, while I had to fight a bit with Spyke. This actually led me to choose Her even though Spyke had better performance, because it seemed that Spyke was too "young". Then, a while into my project, I discovered some things with Her that I really didn't like and I came back to Spyke, and I haven't looked back since :). So, to save some other folks the same round trip, I'd like to share the things that led me to choose Her in the first place, and how Spyke can get better at those.

Firstly, there were som issues with configuration: Mainly #25, #31 and 7e780c58271cdbbb3f472e147a51c97a0cfbfb50. (all my models were wrapped in a namespace)

Then, another biggie for me was if Spyke would work as the base for another gem. In order to do so, Spyke would need to support multiple API:s, not just one. With Her, it was obvious that it would, since they had an API-class for that purpose (and it was mentioned in the readme: https://github.com/remiprev/her/blob/master/README.md#multiple-apis ;)). It wasn't until I basically read through the whole source for Spyke that I discovered that there is a connection method on Spyke::Base (which is included from Spyke::Http) that can just be overriden in order to work with multiple API:s. When making my orginal decision, I had thought I needed to basically fork and include all of Spyke in my gem to make that work.

Once I started reading the source of Spyke, I realized it was well structured and small enough that I could understand how it works. It was also well written, which is more than I can say for some of the code I found in Her (sorry!). So that's why I'm taking time to help Spyke get the few last missing pieces in that makes it outperform Her in every aspect. :)

Then there's the documentation / readme. A lot of my initial issues (such as the one with multiple API:s) could have been avoided if they had been mentioned in the readme. So that’s what this issue is about.

**Comment by balvig** [comment]
@jontebol Thanks for the really nice writeup, was a joy to read :blush: 

Am basically doing "issue-driven readme writing" since this is first and foremost something I use for work myself, so good to hear :+1: 

Was inspired by your post to release a new version that fixes some of the issues you mentioned, as well as adding some stuff I've been using for my own projects. You won't have to override `connection` to use multiple APIs anymore either! :smile:  (see the docs).

**Comment by jontebol** [comment]
Sweet! Nice work! :) I'm sure Spyke will get many new users because of all of these small fixes...
