### ISSUE TITLE
New action

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#33]
Do you have any idea why you did not implemented the new action like her's. I got a problem trying to bypass it with attr_accessors, somehow all my fields that are on accessors are not being sent in the params hash.

**Comment by thiagocifani** [comment]
Basically, what I think I need is some way to generate simpleform forms in a html view using a spyke model, do you think it is possible?

**Comment by balvig** [comment]
Do you have some example code that shows the problem? Maybe then I can help :smile:

**Comment by thiagocifani** [comment]
I need something like 

```ruby
    def new
      @interested_person = Tro::InterestedPerson.new
      authorize @interested_person
    end

    def create
      @interested_person = Tro::InterestedPerson.create(interested_person_update_params)

      if @interested_person
        redirect_to tro_interested_people_path(interested_person), notice: I18n.t("tro.interested_person.created")
      else
        redirect_to new_tro_interested_people_path(interested_person), notice: I18n.t("tro.interested_person.created")
      end
    end


#model

module Tro
  class InterestedPerson < Spyke::Base
    uri "/interested_people/(:id)"

    include_root_in_json "interested_person"

    def self.page(number)
      where(page: number)
    end
  end
end
```

**Comment by thiagocifani** [comment]
```ruby
Tro::InterestedPerson.new

```

should have the fields  I need in my form.

**Comment by balvig** [comment]
And what is in the form?

**Comment by thiagocifani** [comment]
I have solved this problem using simple_form reference to a symbol instead a object, but I am wondering if we should have a new method in the skype to build the object like AR.

**Comment by thiagocifani** [comment]
```ruby
<div class="container" id="parent-container">
  <%= simple_form_for(:interested_person,
                      url: url_for(action: "create", controller: "interested_people"),
                      method: "POST",
                      as: "interested_person",
                      defaults: form_defaults ) do |f| %>
  <div class="page-header">
    <h1>
      Nova Pessoa
      <span class="pull-right">
        <%= f.submit t("defaults.save"), class: "btn btn-primary"%>
        <%= link_to t("defaults.back"), tro_interested_people_url, class: "btn btn-default" %>
      </span>
    </h1>
  </div>

  <%= f.input :name, label: t("tro.interested_person.name") %>
  <%= f.input :email, label: t("tro.interested_person.email") %>
  <%= f.input :telephone, label: t("tro.interested_person.email") %>
  <% end %>
</div>
```

**Comment by thiagocifani** [comment]
if it was @interested_person, and I put some attr_accessors to match this form, my params on my server are filled with those data, but in the api it is empty, seems spyke is not able to recognize fields that I use in get and setters. I could not find the method new used on create in orm.rb

**Comment by balvig** [comment]
Ah okay I think I see. You need to use the `attributes` method to tell Spyke about attributes it doesn't know about from an API, so in this case something like:

```ruby
module Tro
  class InterestedPerson < Spyke::Base
    attributes :name, :email, :telephone
  end
end
```

**Comment by thiagocifani** [comment]
That is exactly what I needed, dont know why I did not think about it before, it is documented somewhere? Thanks in advice

**Comment by balvig** [comment]
Hehe, documentation is still sparse :sweat_smile: 

[Fixtures.rb](https://github.com/balvig/spyke/blob/master/test/support/fixtures.rb) and the [test folder](https://github.com/balvig/spyke/tree/master/test) are the best places to look for usage examples at the moment!

**Comment by thiagocifani** [comment]
Thanks man. great job here.
