### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#35]
Hello @balvig , I am here again. I am trying to reproduce the behavior I got in my api server side, to my frontend side. In your readme you are saying that we can have the same behavior like AR errros handling, but if I am returning something like:

```ruby

model.errors

```

the format is not compatible with yours. What should I do to match with your specification. The return I got is something like

```ruby
#<ActiveModel::Errors:0x007fd4ac83aee0
 @base=
  #<InterestedPerson id: nil, name: "Thiago Cifani", email: "cifani.thiago@gmail.com", telephone: "2298158029", client_id: nil, created_at: nil, updated_at: nil>,
 @messages={:email=>["has already been taken"], :telephone=>["has already been taken"]}>
```
please help me :)

when spyke gets this json, I got

```ruby

#<ActiveModel::Errors:0x007ff7159fca90
 @base=#<Tro::InterestedPerson(/interested_people) id: nil name: "Thiago Cifani" email: "cifani.thiago@gmail.com" telephone: "2298158029">,
 @messages={}>

```
I was not able to find any reference on rails docs about this format you specified on spyke readme

```ruby
errors: { title: [{ error: 'too_short', count: 4 }], groups: [{ error: 'blank' }] }

```

I just found something like

```ruby
 @messages={:email=>["has already been taken"], :telephone=>["has already been taken"]}>
```

How are you using this things?

I have checked here, and I think this place is where everything happens:

https://github.com/balvig/spyke/blob/7b4f1a76509b9e7ba1968900ce2f913fe9c93812/lib/spyke/http.rb#L99

I can change it to fullfill my needs, but I dont know if I am right, need to know your opinion.

**Comment by pedelman** [comment]
I think you will need to write some faraday middleware to parse the response and to format the errors into the appropriate structure.

**Comment by pedelman** [comment]
While we are talking about error formatting, @balvig do you have any plans to introduce a way to wrap errors which are not anything like AR errors? My API I am wrapping is a legacy PHP api and the errors might be something like this:

```rb
[{:status=>409,
  :message=>"A resource conflict prevented the request from being fulfilled.",
  :details=>
   {:conflict_reason=>"A brand called 'bar' already exists.",
    :duplicate_brand=>39}}]
```

**Comment by balvig** [comment]
Ah @thiagocifani sorry, I thought I had already added that to the readme (I have now!), but the format expected is the one that will used by Rails 5 as [described here](https://cowbell-labs.com/2015-01-22-active-model-errors-details.html). You can get the functionality on Rails 4 by installing https://github.com/cowbell/active_model-errors_details :smile: 

@pedelman No plans really! Like you say it would be up to you to do it in the middleware, so that when the errors hash is passed to Spyke it appears in the expected format. You could perhaps just add everything to base ( `{ base: [...] }` ) if you don't get the names of the attributes back for example. It's all up to you! :smile:

**Comment by thiagocifani** [comment]
One more question, do we have the valid? correspondent from rails in spyke object? It is returning true to me even with the array of errors.

**Comment by balvig** [comment]
`valid?` tags along with ActiveModel so it refers to validations defined on the client... :sweat: 
Not sure how to handle this yet! See also the discussion here: https://github.com/balvig/spyke/issues/27

**Comment by thiagocifani** [comment]
I've just override the method on spyke model. 
```ruby
    def valid?
      self.errors.empty?
    end
```

**Comment by balvig** [comment]
Hehe, good workaround for now I think :+1:

**Comment by thiagocifani** [comment]
It is called after create. haha. It is not the perfect approach but I will check the her implementation when I get time to help you with. thanks. I will close it.
