### ISSUE TITLE
Do not understand the description...

### ISSUE THREAD

**Issue by martinstreicher** [balvig/spyke#4]
I am confused by the statement _Like Her, Spyke uses Faraday to handle requests and expects it to return a hash in the following format: `{ data: { id: 1, name: 'Bob' }, metadata: {}, errors: [] }`_

Does that mean the server has to return data in that form? I'd like a better understanding of what goes on the API server and what goes in the API client. Please.

**Comment by balvig** [comment]
Hehe, sure! 

The server can in theory return data in whatever format you like, and it's up to you to add faraday middleware that parses that into a hash in the above format. The readme has one example of this:

```ruby
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    {
      data: json[:result],
      metadata: json[:metadata],
      errors: [json[:message]]
    }
  rescue MultiJson::ParseError => exception
    { errors: [exception.cause] }
  end
end
```

...and this example assumes a JSON server response body that looks something like this:

```json
{ "result": {}, "metadata": {}, "message": "error message" }
```

then in these 5 lines of the faraday middleware:

```ruby
json = MultiJson.load(body, symbolize_keys: true)
{
  data: json[:result],
  metadata: json[:metadata],
  errors: [json[:message]]
}
```

the body is parsed and rearranged into the required:

```ruby
{ data: {}, metadata: {}, errors: ["error message"] }
```

If your data is coming back in a different format then you'll need to tweak this part of the middleware! :smiley_cat: 
Does that make sense? Feel free to ask again, oh and let me know if you have any ideas on how the docs can be clearer :sweat_smile:

**Comment by balvig** [comment]
@martinstreicher I [tweaked the docs a bit](https://github.com/balvig/spyke#configuration) based on your feedback, hope it helps! In any case thanks for pointing it out, closing this for now :smile:

**Comment by martinstreicher** [comment]
That makes sense, yes. What is commonly found in the :metadata key? Or is MultiJson.load producing the keys during parse? I suppose the question is: What’s in body to begin with?

**Comment by balvig** [comment]
The body just contains the raw result from the API, so it could be anything, but the example shows a typical string that would come back from a JSON-based api. MultiJson simply parses this string into a ruby hash that Spyke can use. 

Metadata can be used to send back extra info that aren't part of the actual records. For example, one common thing is information about pagination for collection, ie "current page", "next page", "total count" etc.
