### ISSUE TITLE
Result body data envelope for a resource depend on REST verb

### ISSUE THREAD

**Issue by chinshr** [balvig/spyke#43]
In my case response body depends on the REST request, like for example, `/api/users.json` will have the following json response body:

```
{code: 1, users: [{id: 1, name: "Bob Smith"}, {...}]}
```

While `/api/users/1.json` will have this:

```
{code: 1, user: {id: 1, name: "Bob Smith"}}
```

How would I go about configuring this in Spyke?

**Comment by balvig** [comment]
Off the top of my head, I think you'd have to massage it a bit when parsing in the faraday middleware, for example something like:

```ruby
json = MultiJson.load(body, symbolize_keys: true)
{ data: json[json.keys.first] }
```

Depending on whether you have other keys in there that might not be enough, but the basic idea is the same: Rearrange the JSON so you end up with a hash that matches the `{ data: ..., metadata:..., errors:...}` that Spyke uses :smile:

**Comment by chinshr** [comment]
Got it, thanks for the info! So in my case it would be similar to the following (since I also have a `code` key that I haven't mentioned above, modified my example):

```ruby
json = MultiJson.load(body, symbolize_keys: true){ data: json[json.keys.reject {|k| %w(code errors).include?(k)}.first] }

```

**Comment by balvig** [comment]
Hope it works out for you! :smiley:
