### ISSUE TITLE
Authorization before call

### ISSUE THREAD

**Issue by chinshr** [balvig/spyke#44]
My API requires authorization and needs to use an access token either in the request parameters or inside the header, like `Authorization: $TOKEN`. What is the best practice to do that in Spyke?

**Comment by balvig** [comment]
Basically you'll need to add it through Faraday middleware! For example:

```ruby
class Authentication < Faraday::Middleware
  def call(env)
    env[:request_headers]['Authorization'] = "123mytoken"
    @app.call(env)
  end
end
```

**Comment by chinshr** [comment]
Very nice, I will try that.

**Comment by balvig** [comment]
Good luck! :rocket:
