### ISSUE TITLE
Inspect is broken in some cases

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#45]
Fred and his owner are back! ;) It's actually not inspect that is broken, but something is up with uri and inspect_attributes. This bit me while I was fooling around in a rails console, because the rails console apparently does ```inspect ``` on the return value of every command you enter and suddenly I was getting unexplainable ``` Spyke::InvalidPathError ``` s.

Fred is the broken dog in the following example:
```ruby
class Owner < Spyke::Base; has_many :dogs; end; class Dog < Spyke::Base; belongs_to :owner, uri: "owner/:id"; end

fred = Dog.new
fred.build_owner

fred.owner.uri
# <Spyke::Path:0x000001022d9be8 @params={:id=>nil}, @pattern="owner/:id">
fred.inspect
# Spyke::InvalidPathError: Missing required params: id in owner/:id. Mark optional params with parens eg: (:param)
fred.send(:inspect_attributes)
# Spyke::InvalidPathError: Missing required params: id in owner/:id. Mark optional params with parens eg: (:param)

ted = Dog.new(owner: Owner.new)

ted.owner.uri
# <Spyke::Path:0x00000102249228 @params={}, @pattern="owners/(:id)">
ted.inspect
# "#<Dog(dogs) id: nil owner: #<Owner(owners) id: nil >>"
ted.send(:inspect_attributes)
# "owner: #<Owner(owners) id: nil >"
```

As usual, I may be missing something, but it really seems to me that ```fred = Dog.new; fred.build_owner```would be equivalent to ``` fred = Dog.new(owner: Owner.new) ```. And of course that inspect should never raise an error... ;)

**Comment by balvig** [comment]
Well, welcome back to the both of you :dog: !

You're right of course, inspect should never blow up, and only does it because it's trying to build a path but missing certain attributes in order to do so (ie `owner_id`). 

Perhaps some further playing around with when Path should/shouldn't raise is in order, but for now to ensure this never happens when inspecting https://github.com/balvig/spyke/pull/46 changes Spyke to output the uri _template_ instead, which I think is enough for the debugging purposes that inspect serves? :smile:

**Comment by jontebol** [comment]
Sweet! Thanks for a swift response as usual! 

This doesn't fix the fact that ```fred = Dog.new(owner: Owner.new)``` and ```fred = Dog.new; fred.build_owner``` creates different things for some reason though, right? It might not be a problem a t m, but it sure smells like some kind of trouble. ;)

**Comment by balvig** [comment]
Hehe, basically you are talking about the "setters" of Spyke, that do almost nothing at the moment:

https://github.com/balvig/spyke/blob/inspect/lib/spyke/attribute_assignment.rb#L120

Doing `dog.owner = Owner.new` simply assigns the owner to `attributes[:owner]`.
Meanwhile, when you build an owner in the context of an _association_, Spyke knows that a specific type of URL is required for this object and when necessary knows to assign the id of the parent as a foreign key.

Might be easier to illustrate with a `has_many` example:

```ruby
# Step is built through association: knows parent id and correct url
recipe = Recipe.new(id: 1)
step = recipe.steps.build
step.inspect
# "#<Step(recipes/:recipe_id/steps/:id) id: nil recipe_id: 1>"

# Step is built outside of association, then assigned: has no concept of parent
recipe = Recipe.new(id: 1)
recipe.steps = [Step.new]
recipe.steps.first.inspect
# "#<Step(steps/(:id)) id: nil>"
```

The solution is maybe to have the setters be smarter when it comes to associations, but that's a whole nother story :smile:
