### ISSUE TITLE
Support for find resources with UUID

### ISSUE THREAD

**Issue by risinglf** [balvig/spyke#48]
Hi guys why do you use the strip_slug method in Spyke::Orm.find when searching for a resource?

```ruby
def find(id)
        raise ResourceNotFound if id.blank?
        id = strip_slug(id)
        where(id: id).find_one || raise(ResourceNotFound)
      end
```

This does no allow resources with UUID, or am I wrong?

**Comment by balvig** [comment]
Hey there! 
The reason it's being stripped is to make it easier to work with apps that use "pretty urls", for example:

```ruby
# GET /posts/1-this-is-a-great-post, 
# params[:id] is "1-this-is-a-great-post"
Post.find(params[:id]) # => API calls /posts/1
```

Like Rails, Spyke basically assumes to be working with integers as IDs.
As a workaround perhaps you can use the technique [discussed here](https://github.com/balvig/spyke/issues/16#issuecomment-74364280)?

**Comment by risinglf** [comment]
Hi there,

thanks for your support. 

Actually I mokey patched Spyke in a initializer file to avoid the strip_slug behaviour with this:

```ruby
module Spyke
  module Orm
    module ClassMethods
      def strip_slug(id)
        id.to_s
      end
    end
  end
end
```

I know it smells a lot, but I really don't like to use the find_by method because all my API resources have UUID as primary key.

Maybe we could add add a config option to Spyke to let the user choose the preferred behaviour? What do you think?

**Comment by balvig** [comment]
Hi there!

Sorry for the late reply, currently I need the "strip slug" behavior for the projects I'm working on so am a little hesitant to work on a config I wouldn't use myself :sweat_smile: 

Thanks for pointing out this use case though! I'll keep it in the back of my head going forward! :bow:

**Comment by balvig** [comment]
@risinglf just wanted [I've disabled the slug-stripping for Spyke 4.0](https://github.com/balvig/spyke/commit/0deae87af362dfc188f67fd30d56837e418260d9). Hope it helps!
