### ISSUE TITLE
#all and #find don't really work

### ISSUE THREAD

**Issue by twentyonetwice** [balvig/spyke#51]
Hey,

I'm playing around a bit with spyke and I got a strange behaviour:

If I try `curl 'http://localhost:8529/_db/foxx_test_spyke/spyke_test/users/users/3'` I get the correct response from my database: `{"_key":"3","lname":"Brandybuck","fname":"Meriadoc"}`

Doing the same within the rails console with `User.find(3)` I got `spyke::ResourceNotFound`
The development.log shows me `http://localhost:8529/_db/foxx_test_spyke/spyke_test/users/users/3 [200][0m` (seems like the 200 response)

I'm connected to the db with

    Spyke::Base.connection = Faraday.new(url: 'http://localhost:8529/_db/foxx_test_spyke/spyke_test') do |c|
	  c.request   :json
	  c.use       JSONParser
	  c.adapter   Faraday.default_adapter
    end
and here is the User model :

    class User < Spyke::Base
	  uri 'users/users/(:id)'
	  include_root_in_json false
    end

But when I try to create a user with
`User.create(_key: '5', fname: 'Bilbo', lname: 'Baggins')`
it works as intended. Do you have any idea what's the problem?

**Comment by balvig** [comment]
Could you show me the code for `JSONParser`? Could be something in there. 

Another thing that strikes me is that the returned JSON doesn't have an `id` key, Spyke at the moment expects a field named `id` to work as the primary key.

**Comment by twentyonetwice** [comment]
Oops, I thaught the JSONParser was delivered with Spyke, cause it was so described in the README.

I'll add an id key to the data and give you a feedback whether it succeeds.

**Comment by balvig** [comment]
The JSONParser example in the readme expects the JSON to be wrapped in this format:

```
{ "result": { "id": 1, "name": "Bob" }, "extra": {}, "errors": {} }
```

You'll have to tweak as appropriate to match your own version :smile:

**Comment by twentyonetwice** [comment]
Argh... it would be much better to read the code first before writing such foolish posts...

I'll customize the JSONParser to make it work with my results. Sorry bout the inconvenience!

**Comment by twentyonetwice** [comment]
After tweaking the JSONParser it looks like

```
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    errors = json.delete(:errors) || {}
    metadata = json.delete(:metadata) || {}
    {
	  data: json,
	  metadata: metadata,
	  errors: errors
    }
  rescue MultiJson::ParseError => exception
    { errors: { base: [ error: exception.message ] } }
  end
end
```
and `User.all.first` now works.

I just have to find a way to substitute Spyke's id with the _key of my API.

**Comment by balvig** [comment]
Glad to hear that helped! You could consider rewriting the `_key` part to `id` in the JSON parser too, dunno if that works for your use case, but I think in general Spyke works better if it user `id` as the primary key at the moment...

**Comment by twentyonetwice** [comment]
Hey Jens,

thanks for your patient and your support. It works now as intended with this JSONParser:

    class JSONParser < Faraday::Response::Middleware
	  def parse(body)
		json = MultiJson.load(body, symbolize_keys: true)
		if json.is_a? Array
			json.each do |j|
				j[:id] = j.delete :_key
			end
		else
			json[:id] = json.delete :_key
		end

		errors = json.delete(:errors) || {}
		metadata = json.delete(:metadata) || {}
		{
			data: json,
			metadata: metadata,
			errors: errors
		}
	rescue MultiJson::ParseError => exception
		{ errors: { base: [ error: exception.message ] } }
	end
end
