### ISSUE TITLE
ruby error using #update_attributes

### ISSUE THREAD

**Issue by twentyonetwice** [balvig/spyke#52]
If I want to update the attributes of a model, I got the following message from ruby:
```
NoMethodError: undefined method `to_sym' for nil:NilClass
from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spyke-3.1.3/lib/spyke/http.rb:100:in `block (2 levels) in add_errors_to_model'
```
although Spyke is updating the attributes correctly.
In case that this behaviour is resulting from my JSONParser, I post my customized Parser here:

    class JSONParser < Faraday::Response::Middleware
	  def parse(body)
		json = MultiJson.load(body, symbolize_keys: true)
		if json.is_a? Array
			json.each do |j|
				j[:id] = j.delete :_key
			end
		else
			json[:id] = json.delete :_key
		end

		unless json[:errors].nil?
			errors = json[:errors]
		else
			errors = json.delete(:errors) || {}
		end

		unless json[:extra].nil?
			metadata = json[:extra]
		else
			metadata = json.delete(:extra) || {}
		end

		{
			data: json,
			metadata: metadata,
			errors: errors
		}
	  rescue MultiJson::ParseError => exception
		{ errors: { base: [ error: exception.message ] } }
	  end
    end

**Comment by balvig** [comment]
Could you show me the response JSON from the request?

**Comment by twentyonetwice** [comment]
As I am just testing in rails console, there is no JSON response. The only response I got is from the development log: PUT http://localhost:8529/_db/foxx_test_spyke/spyke_test/users/users/1093677929681

**Comment by twentyonetwice** [comment]
I made a cURL request and got the following response:
```
{
  "attributes": {
    "first_name": "Nate",
    "last_name": "Proudfoot",
    "_id": "spyke_test_users/1093677929681",
    "_rev": "1100639618060",
    "_oldRev": "1100615500812",
    "_key": "1093677929681"
  },
  "isValid": false,
  "errors": {
    "_oldRev": {
      "name": "ValidationError",
      "details": [
        {
          "message": "value is not allowed",
          "path": "value",
          "type": "any.unknown"
        }
      ],
      "_object": "1100615500812"
    }
  },
  "domain": null,
  "_events": {},
  "_maxListeners": 10
}
```
I think that the error is caused by the DB-API, not by Spyke. Although the API obviously responses an error, the data are correctly updated in the database. Very strange ;)

**Comment by balvig** [comment]
Looks like your api isn't following the convention of `ActiveModel::Errors` so maybe in this case you're better off setting errors to `nil` :sweat_smile: 

https://github.com/balvig/spyke#api-side-validations

**Comment by twentyonetwice** [comment]
Looks like my api isn't following any convention :sob:

I'll report this behaviour to their google group and in the meanwhile I set the errors to nil

**Comment by twentyonetwice** [comment]
Just for completion: It was a bug in the api. After fixing the bug the response JSON is:

```
{"attributes"=>{"first_name"=>"Natalie", "last_name"=>"Proudfoot", "_id"=>"spyke_test_users/1093677929681", "_rev"=>"1102050916576", "_oldRev"=>"1102048295136", "_key"=>"1093677929681"},
 "isValid"=>true,
 "errors"=>{},
 "domain"=>nil,
 "_events"=>{},
 "_maxListeners"=>10,
 "id"=>nil}
```
