### ISSUE TITLE
Adding find_by(conditions = {})

### ISSUE THREAD

**Issue by thibaudgg** [balvig/spyke#53]
It would be nice to have quick way of requesting an object without having to deal with `Spyke::ResourceNotFound`.
What about adding `find_by(conditions = {})` that would return the object or `nil` like with Rails?

Thanks!

**Comment by balvig** [comment]
Hey there! 
No plans at the moment, but I suppose you could easily add your own something like this:

```ruby
def self.find_by(conditions)
  where(conditions).first
end
```

**Comment by thibaudgg** [comment]
Yeah it's exactly what I did :). I was just thinking that would be useful for everybody coming from Rails.

**Comment by balvig** [comment]
Hehe, yeh good point, I may be overlooking something, but my concern is it might have to work slightly differently depending on the API, for example:

```ruby
Post.find_by(id: 1) # GET /posts/1 probably returns a single record
Post.find_by(title: 'music') # GET /posts/?title=music probably returns an array
```

That's why I'm putting it off for a bit to avoid running into a leaky abstraction :sweat_smile:

**Comment by thibaudgg** [comment]
I ended up with that in mostly all my models:

```ruby
def self.find_by_id(id)
  id.blank? ? nil : where(id: id).find_one
end
```

**Comment by balvig** [comment]
@thibaudgg I think maybe that's probably the best bet for now! (you could of course extract it to a module or something so all your Spyke models have it)
