### ISSUE TITLE
Custom put request not sending any data

### ISSUE THREAD

**Issue by gottfrois** [balvig/spyke#55]
I have the following model:

```ruby
class Song < Spyke::Base
  attributes :name
end
```

When I do the following, no data is sent in the custom put HTTP request:

```ruby
song = Song.new(id: '1', name: 'some_name')
song.put(:publish)
```

I also tried:

```ruby
song = Song.new(id: '1')
song.name = 'some_name'
song.put(:publish)
```

I would expect the song attributes to be sent in the http request. Any reason not to?

**Comment by balvig** [comment]
Heh, well the intention of the custom requests is something like `publish` or `ban`, which, at least in the use-cases I've encountered, don't require the attributes to be sent along. 

The custom requests takes a hash of params though so if you _do_ need to send the attributes you should be able to do as follows:

```ruby
song.put(:publish, song.attributes)
```

**Comment by gottfrois** [comment]
Sorry for the delay :) Thx for the answer

**Comment by balvig** [comment]
@gottfrois no problem! :balloon:
