### ISSUE TITLE
Handle binary responses from APIs

### ISSUE THREAD

**Issue by risinglf** [balvig/spyke#57]
Hi there,

How can I properly handle with API enpoints that responds a raw file (such as a PDF)?

Eg:

my API has an endpoint called GET /support_files/:id/download

how can I handle with Spyke the request

```
SupportFile.find(id).get(:download)
```

I use this JSONParser as middleware:
```
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    {
        data: json[:data],
        metadata: json[:meta],
        errors: json[:errors]
    }
  rescue MultiJson::ParseError, TypeError => e
    {errors: {base: [error: e.message]}}
  end
end
```

You guys suggest to create another middleware to handle raw data responses? It would be great an example to do that in the wiki ;)

Thank you so much.

**Comment by balvig** [comment]
@risinglf hey there! I guess it depends completely on what you want to do! Spyke is meant to build objects from json/xml/etc responses so giving it a binary file probably won't end well :wink: 
I would probably consider not using Spyke and handling it with a separate class, so it's probably a bit out of scope for this project! :bow:
