### ISSUE TITLE
Unable to use it with faraday default config

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#6]
Hi, I am using your gem with all defaults configs, but I have no idea why, I am unable to make it work. I got a error that said json was not registered, so I investigated a little and added in my gemfile faraday_middleware, but now I am having troubles with net_http. Below follows the error message.

`lookup_middleware': :net_http is not registered on Faraday::Middleware (Faraday::Error)

**Comment by thiagocifani** [comment]
Actually your read installation details was wrong, please, fix it at it follows.


``ruby
  c.adapter       Faraday.default_adapter
``

**Comment by balvig** [comment]
@thiagocifani thanks so much for spotting and reporting that. It's fixed now!
