### ISSUE TITLE
update_attributes within embedded models

### ISSUE THREAD

**Issue by twentyonetwice** [balvig/spyke#60]
Assuming to have this two model

```
class Author < Spyke::Base
  ....
  has_many :books, uri: nil
  attributes :name, :age
end

class Book < Spyke::Base
  ....
  attributes :title, :part
end
```

which results in the following database entry:

```
{
  "name": "J.R.R. Tolkien",
  "age": 102,
  "books": [
    {
      "title": "The Fellowship of the Ring",
      "part": "Part 1"
    }, {
      "title": "The Two Towers",
      "part": "Part 2"
    }, {
      "title": "The Return of the King",
      "part": "Part 3"
    }
  ]
}
```

If I try to edit a book entry, e.g.

    @author = Author.where(name: 'J.R.R. Tolkien').first
    @author.books.last.update_attributes(part: 'Part 4')

The result is

     {"error"=>true, "code"=>404, "errorNum"=>404, "errorMessage"=>"unknown path '/ecasso/books'", "id"=>nil}

where ecasso comes from the db_url.

Is it possible that the update_attributes - method won't work with embedded models?

**Comment by balvig** [comment]
Does the book have an ID in the JSON? Spyke will probably need this to form the correct url to post the update attributes to!

**Comment by twentyonetwice** [comment]
No, they have no ID. This issue is a follow-up of https://github.com/balvig/spyke/pull/59

**Comment by balvig** [comment]
By default `@author.books.last.update_attributes` will try to do a call to `/authors/:author_id/books/:id` (or whatever URI you have set up), so without an ID it won't know which endpoint to use. Maybe what you want is `accepts_nested_attributes_for` to save the book as part of the author? https://github.com/balvig/spyke/blob/master/test/associations_test.rb#L293-L297

**Comment by twentyonetwice** [comment]
Yes, your example is the best way to store embedded models. But I'm looking for a way to edit an attribute's value of a specific embedded model.

To make it clearer: I have a contact model with first_name, last_name etc.

Within this model there's an address model embedded. Each of these embedded documents has an antrribute :active. Only one of these embedded models can have a true active state.

For example:
```
{
  "first_name": "Klaus",
  "last_name": "Humme",
  "addresses": [
    {
      "city": "Somewhere",
      "active": false
    }, {
      "city": "Elsewhere",
      "active": true
    },
  ]
}
```
I have a method which fetches only the active address. If I want to add another address, the current active address' (city: Elsewhere) state maust be set to false and the newly added address is now active.

So if I call #create_new_address in my controller, I want to make something like this:

    current_active = @contact.active_address
    current_active.update_attributes(active: false)
    @contact.addresses.build(some attributes)
    @contact.save

Maybe I'm too dumb to find a way to do this , maybe, too, it's not possible with the default spyke methods. If not, I try to build my own update_attributes method within the addresses model.

**Comment by balvig** [comment]
...or maybe I'm just not understanding properly...hehe :bow: 
API-wise, what would you like to have happen when you call `@contact.save`?

**Comment by twentyonetwice** [comment]
Hey Jens,
thanks a lot for your effort, I appreciate this ;)

@contact.save should write the updated attribute (active: false) of the last active address AND store the new addes address. Both at once, because when the new address is saved to the database, I can only have one active address, that means, only one of the embedded addresses can have the attribute's value of active = true.

With this all-in-once step I want to avoid additional db operations, if one step fails:

I can first edit the active value of @contact.active_address and if this succeeds, the save the new address. But if the saving of the new address fails, I have to make sure, that the state of the last active address must be set to true again.

So I think that all in one might be best solution. 

Ah, but while writing this, I think I can see my mistake... update_attributes writes it instant to the database (no @contact.save needed, right?)

**Comment by balvig** [comment]
> update_attributes writes it instant to the database 

I guess the thing is that you're in "API land" :radio: so every `save` or `create` ends up being an HTTP request somewhere. There is no "writing to the database"! :smile:  

For example:

```ruby
@contact.save => # PUT /contacts/3
@contact.addresses.create => # POST /contacts/3/addresses
```

etc. 

You therefore have to ensure that the different objects have the required ids in order to successfully be sent across to the API. In other words you don't have the complete flexibility of ActiveRecord, but only part of it, which you then have to support in your API.

Hope that makes sense! :sweat_smile:

**Comment by twentyonetwice** [comment]
Yes, I see. My comment was a bit confusing.

As coded in https://github.com/balvig/spyke/blob/master/lib/spyke/orm.rb#L75-L78 ath the end of update_attributes a save is called, which results in a HTTP request and this will write it, in my case, to the database.

But I think that the solution of my problem will be using IDs in embedded documents, too.

**Comment by balvig** [comment]
@twentyonetwice hope things worked out for you! If not feel free to open another issue :smile:
