### ISSUE TITLE
Combine a Spyke model with an ActiveRecord model

### ISSUE THREAD

**Issue by santiagodoldan** [balvig/spyke#61]
Hey,

I'm not sure if this is possible but it would be really nice to be able to do something like this:

```ruby
class User < ActiveRecord::Base
  has_many :comments
end

class Comment < Spyke::Base
end

user = User.find(22)
user.comments # This will hit an API endpoint
```

Thanks :)

**Comment by balvig** [comment]
I have done something similar to that with the following workaround:

```ruby
class User < ActiveRecord::Base
  def comments
    Comment.where(user_id: id)
  end
end
```

It won't give you the full capability of AR, but maybe will be enough for most purposes :smile:

**Comment by santiagodoldan** [comment]
yeah, we are doing that right now, it was just out of curiosity, but as you said that's enough for most of the cases.

thanks :smile:

**Comment by balvig** [comment]
Best of luck! :8ball:
