### ISSUE TITLE
APIAuth support

### ISSUE THREAD

**Issue by santiagodoldan** [balvig/spyke#62]
Is it possible to use APIAuth?

I created a Faraday Middleware but I don't have access to the request object which api-auth receives to create the hmac message.

Thanks

**Comment by santiagodoldan** [comment]
I think this is related to Faraday and not to Spyke. I created a new pull request for Faraday => https://github.com/lostisland/faraday/pull/524

**Comment by balvig** [comment]
Best of luck! :balloon:
