### ISSUE TITLE
Three or more level associations

### ISSUE THREAD

**Issue by oliverzeyen** [balvig/spyke#67]
Actually I'm desperately trying to get a three-level association to work.

```
   class Person < Spyke::Base
      has_many :accounts
   end

   class Account < Spyke::Base
      belongs_to :person
      has_many :authorizations
   end

   class Authorization < Spyke::Base
      belongs_to :account
   end
```

Is there any way to achive such behavior without adding an additional `.where`call at `.authorizations` and pass in the parent idetifiers?

**Comment by balvig** [comment]
Hmmm do you have a usage example of what you're trying to do? :smile:

**Comment by oliverzeyen** [comment]
Actually it would come in quite handy if we could do something like this:
```
   p = Person.all.first # Just as an example

   p.accounts.each do | account |
      … # Do stuff with the account
      accounts.authorizations.each do | authorization |
      … # Do more stuff with an authorization
      end
````

Im able to do so with  `has_many :accounts, uri: '/people/:person_id/accounts/:account_id'` but the I have to call `p.accounts.authorizations.where(person_id: p.id)` because `person_id`get's lost on the last part of the association. Maybe I'm doing something wrong or I'm on the wrong track. The endpoint looks like this this `/people/:person_id/accounts/:account_id/authorizations/:id`.
      
         .

**Comment by balvig** [comment]
Aha, I see what you mean...Unfortunately I can't think of an easy to make that "automagically" work. 

Assuming your JSON contains the required IDs, I suppose you could get close with something like:

```ruby
class Account
  def authorizations
    Authorization.with("people/:person_id/accounts/:account_id/authorizations/:id").where(person_id: person_id, account_id: id)
  end
end
```

But even that of course won't work in all situations, but might get be enough for your purpose? :sweat:

**Comment by balvig** [comment]
@oliverzeyen closing this for now! Hoping you came up with a solution ☮️

**Comment by louman** [comment]
hey, I'm in a pretty similar situation and can say @balvig 's suggestion works. Without having looked at the code, wondering if it would be possible to add a ```where``` option to the association definition so you can pass where to pull the missing params from.
