### ISSUE TITLE
Push tags for gem releases

### ISSUE THREAD

**Issue by luislavena** [balvig/spyke#7]
Hello,

Thank you for releasing this project as open source and provide alternatives to other existing ones.

We were trying to determine the changes between today's release (1.6.0) and previous one for auditing purposes but we couldn't find tags in the repository to perform comparisons.

It will be great if you can push the tags of each of the versions so we can audit, inspect and compare the changes across versions.

Once again, thank you for releasing this.

**Comment by balvig** [comment]
@luislavena Oh dear thanks for pointing that out! For some reason had the impression my gem release tool was already doing that automatically...anyway, I've retroactively tagged and [pushed to github](https://github.com/balvig/spyke/tags), hope it helps! :grin:
