### ISSUE TITLE
default scope for Spyke model

### ISSUE THREAD

**Issue by therrick** [balvig/spyke#71]
I'm using spyke to connect two rails applications that are each use the ActsAsTenant gem to achieve multitenancy. 

Each application has a Tenant model with codes that identify the tenants, and all records are marked according with the tenant they belong to. ActsAsTenant provides a current_tenant thread-level global that identifies the current user's tenant and all the tenant-based models have a default scope to filter by the current_tenant (or throw an error if the current_tenant is not set). This is all standard functionality of the ActsAsTenant gem.

What I want to do is to pass the current_tenant.code in each request that spyke makes so that the remote side can apply the same filtering that would be applied locally. I thought this would work...

```
class User < Spyke::Base
  uri "users/(:id)?tenant_code=#{ ActsAsTenant.current_tenant.try(&:code) }"
end
```

but the problem is that the URI string is only evaluated the first time the model is referenced, so if the current_tenant changes, subsequent requests use the original URI with the wrong tenant.

Ideally, I'd like something like this...

```
class User < Spyke::Base
  default_scope { where(tenant_code: ActsAsTenant.current_tenant.try(&:code)) }
  uri "users/(:id)"
end
```

but there's no support for a default scope.

What I ended up with is this...

```
class User < Spyke::Base
  scope :with_tenant, -> { where(tenant_code: ActsAsTenant.current_tenant.try(&:code)) }
  uri 'users/(:id)'

  before_save :set_tenant

  def set_tenant
    attributes['tenant_code'] = ActsAsTenant.current_tenant.try(&:code)
  end
end
```

Then I have to specify 'User.with_tenant' whenever I reference the User model. The before_save hook is also necessary because the with_tenant scope doesn't get applied to updates.

It seems like there must be a better way to accomplish this, but I can't figure it out. Any suggestions?

**Comment by balvig** [comment]
Hi @therrick! Thanks for submitting this issue.

To be honest, my personal experience with `default_scope` (in _ActiveRecord_ that is) is that I usually end up regretting using it :) For example I would find myself logging into the console wanting to look for a particular user by id, and then forgetting to set the correct tenant first etc. 

Therefore, I have ended up preferring to use something like `User.with_tenant` explicitly where needed, even though it might feel a bit redundant at times...I feel like maybe the only use case that I have come across where `default_scope` really works well is with "soft deletes", as in this case you really don't want to see those records most of the time, even in the console.

I guess this is the reason I didn't implement it for Spyke 😅 

In any case, that's probably not the answer you were looking for... 😓  🙇  I feel like your solution is pretty good/lightweight though? I would be interested to hear how it goes with that workaround at least!

**Comment by therrick** [comment]
Thanks for the quick response.

Yeah, I understand the reluctance around default_scope -- it definitely has it's pitfalls. But it does seem to have valid uses and the example you gave for soft-deletes is a good one. The way it is used in ActsAsTenant is similarly useful to universally protect against querying data from a different tenant.

I'm not hung up on using a default scope. It just seems like there must be some way to always append a dynamic variable in the request. I thought maybe I could use the uri variable syntax (e.g. `uri 'users/(:id)?tenant_code=:current_tenant_code'), maybe with a function defined in the class to lookup the current code, but that doesn't seem to work either. 

I can live with the with_tenant workaround. Just thought I'd check one more time to see if you can think of some feature I could take advantage of in either spyke or faraday to implement this in a way that's more transparent to the calling code.

Thanks.

**Comment by balvig** [comment]
Very cool, thanks! 

It's great to hear about these things, helps when I one day run into the issue myself and go "oooh...." 😅

**Comment by mattboldt** [comment]
@balvig Bumping this thread, as I have a _similar_ necessity for a default scope, but for associations. Example:

```ruby
class Post < Spyke::Base
  uri 'api/posts/(:id)'
  has_many :comments
end

class Comments < Spyke::Base
  uri 'api/comments/(:id)'
  belongs_to :post
end

post = Post.find(1)
#=> GET api/posts/1 👍 

post.comments
#=> GET api/posts/1/comments 🚫  👎 
# I don't have nested routes on my API. I have a flat resource structure with filters.
```
What I'd like to do instead:
```ruby
class Post < Spyke::Base
  uri 'api/posts/(:id)'
  has_many :comments, uri: 'api/comments?filter[post_id]=:post_id', foreign_key: :post_id 
end

post.comments
#=> GET api/comments?filter[post_id]=1 🎉  hooray!

post.comments.where(filter: { status: :pending })
#=> GET api/comments?filter[status]=pending 😭  uh oh
```
We can see in that last example my "default scope" filter got removed because the URI conflicts with the `where` options passed. Here's how I resolved this: when building the request itself, I check if the base URI includes query params. If so, I merge them with any incoming params. This happens in the [Spyke http module](https://github.com/balvig/spyke/blob/d962034cc9298cdf031b358bc76571b914bf89f1/lib/spyke/http.rb)
```ruby
module Spyke
  module Http
    module ClassMethods
      private
      def scoped_request(method)
        uri = new.uri
        params = current_scope.params.except(*uri.variables)

        # Expand path template to full path, e.g. `api/v1/posts/:id => api/v1/posts/123`
        path = uri.to_s

        # Build URI object from path
        path_uri = URI(path)

        # Parse the query string into a hash with symbolized keys
        uri_query = Rack::Utils.parse_nested_query(path_uri.query || {}).symbolize_keys

        # ONLY If the base query contains filter params, we need to merge them
        # with the current incoming params.
        # Else, leave the path and params alone.
        if uri_query.key?(:filter) && uri_query[:filter].is_a?(Hash)

          # Only symbolize nested keys once we know we need to merge them
          # I'm assuming this is a perf hit, so I only want to do it if necessary
          uri_query.deep_symbolize_keys!

          # Remove query params (if any) from base bath
          path = path_uri.path

          # Build a new `filter` hash if one does not already exist
          params[:filter] = {} unless params.key?(:filter)

          # If an incoming `filter` param exists but is not a hash, do nothing
          if params[:filter].is_a?(Hash)
            # Merge the original URL filter param with the incoming params
            # The INCOMING filter params override ORIGINAL params if there are collisions
            params[:filter] = uri_query[:filter].merge(params[:filter])
          end
        end

        # Send path and params back to Spyke to perform the request
        request(method, path, params)
      end
    end
  end
end
```
With the above patch, I'm able to achieve the following:
```ruby
post.comments.where(filter: { status: :pending })
#=> GET api/comments?filter[post_id]=1&filter[status]=pending 🎉 
```
It does not feel great to patch a lower-level class like `Spyke::Http`, but since this is where the URI template gets populated and converted to a real path, and where the `params` are sent to the request, it was the only spot I could tell would be easy to override. However, I'm curious if you have thoughts on this approach and if you could point me in a better direction to add this sort of feature.

I'm thinking a public API could look something like this? Then the URI could stay untouched, but we would need to evaluate the `scope`, inject the foreign_key value, and merge it with the incoming params. Not sure where this is best handled.
```ruby
class Post < Spyke::Base
  has_many :comments, uri: 'api/comments', scope: { filter: :post_id } 
end

```

**Comment by balvig** [comment]
Thank you @mattboldt, could you make take a look at https://github.com/balvig/spyke/pull/122 and see if that solves your problem? 🙏
