### ISSUE TITLE
Support for activesupport 3.2

### ISSUE THREAD

**Issue by sthaha** [balvig/spyke#72]
I see that in [spec file](https://github.com/balvig/spyke/blob/master/spyke.gemspec#L21-L22) it mentions `3.0 >=` but seems to be depending on [features](626af467) introduced in 4.0.0 (`ActiveModel::Model`). 
Should the spec be changed to reflect it?

**Comment by balvig** [comment]
Aha yes! That would make sense 🙇

**Comment by balvig** [comment]
@sthaha thanks for the reminder! Fixed in #74
