### ISSUE TITLE
Support for Rails 5, (activerecord & activemodel 5.0.0)

### ISSUE THREAD

**Issue by edelgado** [balvig/spyke#73]
Hi folks!

I noticed that Spyke locks its dependency to `activemodel` < `5.0`, >= `3.0.0` and `activesupport` < `5.0`, >= `3.0.0`. How difficult is it to support 5.0.0 versions?

Thanks 😄

**Comment by balvig** [comment]
Probably shouldn't be too hard, in fact it might "just work", simply haven't tested it yet! :)

**Comment by balvig** [comment]
Thanks for the reminder @edelgado, fixed in #74

**Comment by edelgado** [comment]
Thanks @balvig 💯
