### ISSUE TITLE
Header = nil when methods are chained

### ISSUE THREAD

**Issue by LucasCioffi** [balvig/spyke#75]
Thanks for making this gem.  Here's something I found in case it's helpful:

Spyke makes two API calls when `.find` and `.update` are chained in the code below, but the header = nil on the second call.
```
TestClient::Measurement.with("custom_route_goes_here")
  .find(params[:measurement_id])
  .update(params[:measurement])
```

This doesn't happen with `.destroy` however.

**Comment by balvig** [comment]
Hi @LucasCioffi! Which header are you referring too?

**Comment by LucasCioffi** [comment]
Hi @balvig this refers to the request header coming from the application which has Spyke and going to an application that uses Grape API.  We're using a user auth token to authenticate each request, so when the second request comes in without a header, we are not able to authenticate the user.

Is there a way to update a record with only one HTTP request?

**Comment by balvig** [comment]
How are you setting the headers?

**Comment by LucasCioffi** [comment]
Thank you for your help, @balvig. I am manually setting the headers using Postman, a Chrome plugin for making API requests.

**Comment by balvig** [comment]
@LucasCioffi I'm really sorry, but I'm not completely understanding your problem! 🙇 

Spyke doesn't provide any particular functionality for setting headers, this is something you would normally do in the Faraday middleware.

Not sure how using Postman to set headers fits in with your code example either 😢 

To answer your other question:

> Is there a way to update a record with only one HTTP request?

I guess you could maybe make use of one of these techniques? https://github.com/balvig/spyke/blob/ea0969e3bb7e25acc131e5f1a89114d0ef4087a4/test/orm_test.rb#L46-L75

Hope it helps!

**Comment by balvig** [comment]
@LucasCioffi if you don't mind I'll close this for now, let me know if you're still having trouble.

**Comment by LucasCioffi** [comment]
👍 Thanks again!
