### ISSUE TITLE
Doesn't cache result of associated object(s)

### ISSUE THREAD

**Issue by paulvt** [balvig/spyke#77]
When a model has a relation, Spyke keeps trying to retrieve it instead of caching/remembering it.
For example, consider the following model

```ruby
class Account
  belongs_to :company
  has_many :apps
end

account = Account.all.first
```

Then doing things like `account.company.name`, `account.company.address`, etc. but also `account.apps.first` keep leading to new GET requests.  I would assume once retrieved, the associated object(s) are attached to the parent (like what Rails and Her do).

**Comment by sschepens** [comment]
It would also be great if Spyke could have something similar to Rails' QueryCache, basically it's a threadlocal cache so that when you repeat the same query (say `#find(1)`) only one query is actually executed and the second one uses the cache,  Rails clears the cache after every request using a middleware.

**Comment by balvig** [comment]
Thanks, that all sounds handy! 
If you're ever up for taking a crack at a PR would be great :)

**Comment by paulvt** [comment]
I just tried out this naive implementation of association caching by updating found results in the parents, so it doesn't look them up anymore, as follows:

```diff
diff --git i/lib/spyke/associations/association.rb w/lib/spyke/associations/association.rb
index 5ecfec3..c087c37 100644
--- i/lib/spyke/associations/association.rb
+++ w/lib/spyke/associations/association.rb
@@ -29,6 +29,14 @@ def new(*args)
 
       alias :build :new
 
+      def find_one
+        update_parent super
+      end
+
+      def find_some
+        update_parent super
+      end
+
       private
 
         def add_to_parent(record)
```

This works already quite well and is similar to what Her does.  It does breaks some tests of course and  I ran into a problem.
If you do `group = Recipe.find(1).groups` and then `groups.find(1)` the object in `recipe.groups` is completely broken and I cannot seem to find what does this?

**Comment by paulvt** [comment]
Nevermind, the find only yields one result in this case and this will be stuffed in the groups attribute after which it is not at all what Spyke expects to be, namely a list of results.
