### ISSUE TITLE
Why use an exception for not found resources

### ISSUE THREAD

**Issue by paulvt** [balvig/spyke#78]
Following up to issue #76, an issue is that one needs to make the parser middleware such that the `ResourceNotFound` exception is thrown in case of a 404, because `#new_instant_from_result` does not check the presence of data but just its non-nillness.  I would propose the following change:

```diff
--- i/lib/spyke/http.rb
+++ w/lib/spyke/http.rb
@@ -36,7 +36,7 @@ def request(method, path, params = {})
       end
 
       def new_instance_from_result(result)
-        new_or_return result.data if result.data
+        new_or_return result.data if result.data.present?
       end
 
       def new_collection_from_result(result)
```

Note that this accidentally goes right in `test_404` because it contains a message and the JSON parser from the test just takes `json[:result]`.

**Comment by sschepens** [comment]
@paulvt `#find` on active record raises an exception when the record is not found.
The methods that do not raise exceptions are the familiy of `#find_by` unless you use the  `#find_by!` family.

**Comment by paulvt** [comment]
@sschepens My mistake, you are correct. I got confused with Her that does return `nil` and AR being not so consistent here. IMO `#find!# should raise the exception and `#find` not, but that's for another day.

**Comment by paulvt** [comment]
I updated the issue text to reflect this insigh.  I couldn't change the title though.

**Comment by balvig** [comment]
Hello @paulvt, basically Spyke is modelled on ActiveRecord where `Model#find` raises an exception. Thanks @sschepens for chiming in :)

**Comment by balvig** [comment]
Let me know if you need more info on this, feel free to reopen if so!
