### ISSUE TITLE
Process XML response?

### ISSUE THREAD

**Issue by chriso0710** [balvig/spyke#81]
Hi all,

Would it be possible to process responses from an API which returns XML? Can Spyke build objects from XML body data?
Does anyone have a documentation or starting point for this?

Thanks and regards
Christian

**Comment by balvig** [comment]
It certainly can! In fact Spyke doesn't care what the format is, at it's up to you to convert the response data into a hash before passing it on to Spyke:

https://github.com/balvig/spyke#configuration

Instead of 

```ruby
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    {
      data: json[:result],
      metadata: json[:extra],
      errors: json[:errors]
    }
  end
end
```

you would have something like

```ruby
class XMLParser < Faraday::Response::Middleware
  def parse(body)
    xml = YourFavoriteXMLLibrary.parse(xml)
    {
      data: xml[:result],
      metadata: xml[:extra],
      errors: xml[:errors]
    }
  end
end
```

**Comment by chriso0710** [comment]
Thanks @balvig, I will give it a try.
