### ISSUE TITLE
Invalid path error thrown too early for URIs with other IDs

### ISSUE THREAD

**Issue by paulvt** [balvig/spyke#90]
If the URI of a relation contains another (parent) ID, retrieving the object fails with a `Skype::InvalidPathError` before it is even checked whether the ID is not `nil`. The expected behaviour would be to just return `nil` if the ID for the relation is not set. For example:

```ruby
class Recipe < Spyke::Base
  belongs_to :user
  has_many :ingredients
end

class User < Spyke::Base
end

class Ingredient
  belongs_to :group, uri: "ingredients/:ingredient_id/groups/:id"
end

class Group < Spyke::Base
end

recipe = Recipe.find(1)
recipe.user_id # => nil
recipe.user # => nil

ingredient = recipe.ingredients.first
ingredient.group_id # => nil
ingredient.group # => raises Spyke::InvalidPathError instead of returning nil
```

More specifically, the last call raises the exception:
```
Spyke::InvalidPathError: Missing required variables: ingredient_id, id in ingredients/:ingredient_id/group. Mark optional variables with parens eg: (:param)
```

**Comment by balvig** [comment]
Thanks for submitting the issue @paulvt! 

Would it be possible to include the JSON responses for the examples? I _think_ the `InvalidPathError` might be getting raised because the `id` is missing from the first ingredient `recipe.ingredients.first`, but I'm not entirely sure.

Even better if you can reproduce the problem with a test, for example taking inspiration from https://github.com/balvig/spyke/blob/master/test/associations_test.rb

**Comment by paulvt** [comment]
Ok, the problem seems to be unrelated to chaining/nesting of relations (and thus #89). The issue seems to be that an `InvalidPathError` exception is thrown if the ID is missing to retrieve the object. This is somewhat unexpected behaviour to us. If the ID is not set, there is just no related object IMO.

The test to show what I mean is as follows:
```ruby
    def test_return_nil_for_missing_id
      stub_request(:get, 'http://sushi.com/recipes/1').to_return_json(result: { id: 1, user_id: "1" } )
      stub_request(:get, 'http://sushi.com/recipes/2').to_return_json(result: { id: 2 })
      stub_request(:get, 'http://sushi.com/users/1').to_return_json(result: { id: 1 })

      recipe = Recipe.find(1)
      assert_equal 1, recipe.user.id

      recipe = Recipe.find(2)
      assert_nil recipe.user
    end
```

For recipe with ID 1, the user is known and retrievable. For recipe with ID 2, the user is unknown and no retrieval attempt should be made instead of throwing the exception.  This should be analogue to when the data would have been embedded, `nil` or as `{ uuid: 1, name: "paulvt", ... }`

**Comment by balvig** [comment]
@paulvt aha I see! Thanks, the test makes it a lot clearer, I've started a branch [here](https://github.com/balvig/spyke/compare/belongs_to)

**Comment by balvig** [comment]
@paulvt not sure if the approach I'm taking in https://github.com/balvig/spyke/compare/belongs_to is the best yet, but could you maybe give it a try to see if it solves your problem?

**Comment by paulvt** [comment]
Yeah, I already had an inkling that the URL was constructed before checking if the necessary attributes, in this case the primary key, were present. So, this seems good.  I have also tested with the branch and this indeed fixes the problem!

**Comment by balvig** [comment]
Awesome, thanks @paulvt! I will do some more testing and then look to releasing a new version
