### ISSUE TITLE
Help on encapsulated responses

### ISSUE THREAD

**Issue by dunyakirkali** [balvig/spyke#98]
Hi,

I have here an api which returns the responses encapsulated in an object with the objects name.
So if I call `v1/user/1912` I get the following back:

```
{
  "Response": {
    "User": {
      "Name": "Dunya"
    }
  }
}
```

I could of course have the following JSONParser:

```
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    {
      data: json[:Response][:User],
      metadata: {},
      errors: json[:Error]
    }
  end
end
```

But then how would I have the `[:User]` bit generic?

**Comment by balvig** [comment]
Would

```ruby
json[:Response].first.last
```

do the trick?

**Comment by dunyakirkali** [comment]
Will do that. Thanx
